import GlobalContext from '../global-context';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <GlobalContext>{children}</GlobalContext>
      </body>
    </html>
  );
}
